services:
  - type: web
    name: monument-backend
    runtime: docker
    repo: https://github.com/sirisampathb/FSAD_Backend
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_HOST
        fromDatabase:
          name: monument-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: monument-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: monument-db
          property: database
      - key: DATABASE_USERNAME
        fromDatabase:
          name: monument-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: monument-db
          property: password
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: PORT
        value: 8080
    healthCheckPath: /api/health

databases:
  - name: monument-db
    plan: free
    databaseName: monumentdb
    user: monument_user
